#!/usr/bin/env node
/**
 * Build Configuration Script for Chrome Extension
 *
 * Reads environment variables from .env file and generates config.js
 * that can be used by the extension at runtime.
 *
 * Usage:
 *   node scripts/build-config.js [--production]
 */

const fs = require('fs');
const path = require('path');

// Parse command line arguments
const isProduction = process.argv.includes('--production') || process.env.NODE_ENV === 'production';

// Load .env file
function loadEnvFile() {
  const envPath = path.join(__dirname, '..', '.env');
  const envExamplePath = path.join(__dirname, '..', '.env.example');

  // Try .env first, fall back to .env.example
  let envFile = envPath;
  if (!fs.existsSync(envPath)) {
    console.warn('Warning: .env file not found, using .env.example');
    envFile = envExamplePath;
  }

  if (!fs.existsSync(envFile)) {
    console.error('Error: Neither .env nor .env.example found!');
    process.exit(1);
  }

  const envContent = fs.readFileSync(envFile, 'utf8');
  const env = {};

  envContent.split('\n').forEach(line => {
    // Skip comments and empty lines
    line = line.trim();
    if (!line || line.startsWith('#')) return;

    const [key, ...valueParts] = line.split('=');
    if (key && valueParts.length > 0) {
      let value = valueParts.join('=').trim();
      // Remove quotes if present
      if ((value.startsWith('"') && value.endsWith('"')) ||
          (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      env[key.trim()] = value;
    }
  });

  return env;
}

// Generate config.js content
function generateConfig(env) {
  const config = {
    // API Configuration
    API_URL: env.API_URL || 'http://localhost:4100/api',
    EXTENSION_API_URL: `${env.API_URL || 'http://localhost:4100/api'}/extension`,
    WS_URL: env.WS_URL || 'ws://localhost:4100',

    // Web Frontend
    WEB_URL: env.WEB_URL || 'http://localhost:4000',

    // Extension Info
    EXTENSION_NAME: env.EXTENSION_NAME || 'Fireflies',
    EXTENSION_ENV: isProduction ? 'production' : (env.EXTENSION_ENV || 'development'),

    // Feature Flags
    ENABLE_ANALYTICS: env.ENABLE_ANALYTICS !== 'false',
    ENABLE_ERROR_REPORTING: env.ENABLE_ERROR_REPORTING !== 'false',
    ENABLE_AUTO_RECORD: env.ENABLE_AUTO_RECORD !== 'false',

    // Derived URLs
    get AUTH_URL() { return `${this.API_URL}/auth`; },
    get MEETINGS_URL() { return `${this.API_URL}/meetings`; },
    get SESSIONS_URL() { return `${this.EXTENSION_API_URL}/sessions`; },
    get ANALYTICS_URL() { return `${this.API_URL}/analytics`; },
    get ERROR_REPORT_URL() { return `${this.EXTENSION_API_URL}/error-report`; },

    // Web URLs
    get DASHBOARD_URL() { return `${this.WEB_URL}/dashboard`; },
    get SETTINGS_URL() { return `${this.WEB_URL}/settings`; },
    get MEETINGS_PAGE_URL() { return `${this.WEB_URL}/meetings`; },
    get REGISTER_URL() { return `${this.WEB_URL}/register`; },
    get HELP_URL() { return `${this.WEB_URL}/help`; },
    get PRIVACY_URL() { return `${this.WEB_URL}/privacy`; },
    get TERMS_URL() { return `${this.WEB_URL}/terms`; },
  };

  // Generate the config.js file content
  // We use a self-executing function to create the Config object with getters
  return `/**
 * Extension Configuration
 *
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/build-config.js
 * Generated at: ${new Date().toISOString()}
 * Environment: ${config.EXTENSION_ENV}
 */

const Config = (function() {
  const config = {
    // API Configuration
    API_URL: '${config.API_URL}',
    EXTENSION_API_URL: '${config.EXTENSION_API_URL}',
    WS_URL: '${config.WS_URL}',

    // Web Frontend
    WEB_URL: '${config.WEB_URL}',

    // Extension Info
    EXTENSION_NAME: '${config.EXTENSION_NAME}',
    EXTENSION_ENV: '${config.EXTENSION_ENV}',
    IS_PRODUCTION: ${config.EXTENSION_ENV === 'production'},
    IS_DEVELOPMENT: ${config.EXTENSION_ENV === 'development'},

    // Feature Flags
    ENABLE_ANALYTICS: ${config.ENABLE_ANALYTICS},
    ENABLE_ERROR_REPORTING: ${config.ENABLE_ERROR_REPORTING},
    ENABLE_AUTO_RECORD: ${config.ENABLE_AUTO_RECORD},
  };

  // Add derived URLs as getters for cleaner access
  Object.defineProperties(config, {
    // API URLs
    AUTH_URL: { get: () => config.API_URL + '/auth' },
    MEETINGS_API_URL: { get: () => config.API_URL + '/meetings' },
    SESSIONS_URL: { get: () => config.EXTENSION_API_URL + '/sessions' },
    ANALYTICS_URL: { get: () => config.API_URL + '/analytics' },
    ERROR_REPORT_URL: { get: () => config.EXTENSION_API_URL + '/error-report' },
    VERIFY_CONNECTION_URL: { get: () => config.EXTENSION_API_URL + '/verify-connection' },
    STATS_URL: { get: () => config.EXTENSION_API_URL + '/stats' },

    // Web URLs
    DASHBOARD_URL: { get: () => config.WEB_URL + '/dashboard' },
    SETTINGS_URL: { get: () => config.WEB_URL + '/settings' },
    MEETINGS_PAGE_URL: { get: () => config.WEB_URL + '/meetings' },
    REGISTER_URL: { get: () => config.WEB_URL + '/register' },
    HELP_URL: { get: () => config.WEB_URL + '/help' },
    PRIVACY_URL: { get: () => config.WEB_URL + '/privacy' },
    TERMS_URL: { get: () => config.WEB_URL + '/terms' },
  });

  // Freeze config to prevent modifications
  return Object.freeze(config);
})();

// Export for different module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = Config;
}
`;
}

// Main execution
function main() {
  console.log(`Building extension config (${isProduction ? 'production' : 'development'})...`);

  const env = loadEnvFile();
  const configContent = generateConfig(env);

  const outputPath = path.join(__dirname, '..', 'config.js');
  fs.writeFileSync(outputPath, configContent);

  console.log(`Config generated: ${outputPath}`);
  console.log(`  API_URL: ${env.API_URL || 'http://localhost:4100/api'}`);
  console.log(`  WEB_URL: ${env.WEB_URL || 'http://localhost:4000'}`);
  console.log(`  Environment: ${isProduction ? 'production' : (env.EXTENSION_ENV || 'development')}`);
}

main();
