/**
 * Extension Configuration
 *
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 * Generated by: scripts/build-config.js
 * Generated at: 2025-12-10T19:20:35.755Z
 * Environment: production
 */

const Config = (function() {
  const config = {
    // API Configuration
    API_URL: 'http://localhost:4100/api',
    EXTENSION_API_URL: 'http://localhost:4100/api/extension',
    WS_URL: 'ws://localhost:4100',

    // Web Frontend
    WEB_URL: 'http://localhost:4200',

    // Extension Info
    EXTENSION_NAME: 'Nebula AI',
    EXTENSION_ENV: 'production',
    IS_PRODUCTION: true,
    IS_DEVELOPMENT: false,

    // Feature Flags
    ENABLE_ANALYTICS: true,
    ENABLE_ERROR_REPORTING: true,
    ENABLE_AUTO_RECORD: true,
  };

  // Add derived URLs as getters for cleaner access
  Object.defineProperties(config, {
    // API URLs
    AUTH_URL: { get: () => config.API_URL + '/auth' },
    MEETINGS_API_URL: { get: () => config.API_URL + '/meetings' },
    SESSIONS_URL: { get: () => config.EXTENSION_API_URL + '/sessions' },
    ANALYTICS_URL: { get: () => config.API_URL + '/analytics' },
    ERROR_REPORT_URL: { get: () => config.EXTENSION_API_URL + '/error-report' },
    VERIFY_CONNECTION_URL: { get: () => config.EXTENSION_API_URL + '/verify-connection' },
    STATS_URL: { get: () => config.EXTENSION_API_URL + '/stats' },

    // Web URLs
    DASHBOARD_URL: { get: () => config.WEB_URL + '/dashboard' },
    SETTINGS_URL: { get: () => config.WEB_URL + '/settings' },
    MEETINGS_PAGE_URL: { get: () => config.WEB_URL + '/meetings' },
    REGISTER_URL: { get: () => config.WEB_URL + '/register' },
    HELP_URL: { get: () => config.WEB_URL + '/help' },
    PRIVACY_URL: { get: () => config.WEB_URL + '/privacy' },
    TERMS_URL: { get: () => config.WEB_URL + '/terms' },
  });

  // Freeze config to prevent modifications
  return Object.freeze(config);
})();

// Export for different module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = Config;
}
