'use client';

import { useState } from 'react';
import {
  Eye, Copy, Download, Share2, Maximize2, Code, FileText,
  CheckCircle, RefreshCw, Edit, Save, X, ChevronLeft,
  ChevronRight, Sparkles, FileJson, FileCode, Mail
} from 'lucide-react';
import { CardGlass, CardGlassContent, CardGlassDescription, CardGlassHeader, CardGlassTitle } from '@/components/ui/card-glass';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { Alert, AlertDescription } from '@/components/ui/alert';
import type { AIApp } from './AppMarketplace';

interface AppOutputPreviewProps {
  app?: AIApp;
  output?: string;
  format?: 'markdown' | 'json' | 'html' | 'plain' | 'email';
  timestamp?: string;
  meetingTitle?: string;
  onEdit?: (newOutput: string) => void;
  onRegenerate?: () => void;
  onExport?: (format: string) => void;
}

export default function AppOutputPreview({
  app,
  output,
  format = 'markdown',
  timestamp,
  meetingTitle,
  onEdit,
  onRegenerate,
  onExport
}: AppOutputPreviewProps) {
  const [isEditing, setIsEditing] = useState(false);
  const [editedOutput, setEditedOutput] = useState(output || '');
  const [viewMode, setViewMode] = useState<'preview' | 'raw'>('preview');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [copied, setCopied] = useState(false);

  // Sample outputs for different formats
  const sampleOutputs = {
    markdown: `# Meeting Summary

**Date:** January 25, 2024
**Participants:** John Smith, Sarah Johnson, Mike Chen
**Duration:** 45 minutes

## Key Discussion Points

1. **Q4 Revenue Review**
   - Total revenue exceeded targets by 12%
   - Strong performance in enterprise segment
   - New customer acquisition up 25% YoY

2. **Product Roadmap Updates**
   - AI features launch planned for Q2
   - Mobile app redesign in progress
   - API v2 beta testing starting next week

## Action Items

- [ ] **John Smith**: Prepare detailed Q4 report by EOW
- [ ] **Sarah Johnson**: Schedule customer feedback sessions
- [ ] **Mike Chen**: Review and approve API documentation

## Decisions Made

- Approved budget increase for marketing campaigns
- Decided to postpone feature X to Q3
- Confirmed partnership with TechCorp

## Next Steps

1. Follow-up meeting scheduled for February 1st
2. Share meeting notes with extended team
3. Begin implementation of approved initiatives

---
*Generated by AI Meeting Summarizer*`,

    json: JSON.stringify({
      meeting: {
        date: "2024-01-25",
        duration: "45 minutes",
        participants: ["John Smith", "Sarah Johnson", "Mike Chen"],
        summary: {
          keyPoints: [
            "Q4 revenue exceeded targets by 12%",
            "AI features launch planned for Q2",
            "Partnership with TechCorp confirmed"
          ],
          actionItems: [
            {
              assignee: "John Smith",
              task: "Prepare detailed Q4 report",
              dueDate: "2024-01-28",
              priority: "high"
            },
            {
              assignee: "Sarah Johnson",
              task: "Schedule customer feedback sessions",
              dueDate: "2024-02-01",
              priority: "medium"
            }
          ],
          decisions: [
            "Approved budget increase for marketing",
            "Postponed feature X to Q3"
          ]
        }
      }
    }, null, 2),

    html: `<!DOCTYPE html>
<html>
<head>
  <title>Meeting Summary</title>
  <style>
    body { font-family: Arial, sans-serif; }
    h1 { color: #333; }
    .section { margin: 20px 0; }
    .action-item { padding: 10px; background: #f5f5f5; margin: 5px 0; }
  </style>
</head>
<body>
  <h1>Meeting Summary</h1>
  <div class="section">
    <h2>Key Points</h2>
    <ul>
      <li>Q4 revenue exceeded targets</li>
      <li>New product features approved</li>
    </ul>
  </div>
  <div class="section">
    <h2>Action Items</h2>
    <div class="action-item">
      <strong>John Smith:</strong> Prepare Q4 report
    </div>
  </div>
</body>
</html>`,

    plain: `MEETING SUMMARY
===============

Date: January 25, 2024
Participants: John Smith, Sarah Johnson, Mike Chen
Duration: 45 minutes

KEY DISCUSSION POINTS:
- Q4 revenue exceeded targets by 12%
- AI features launch planned for Q2
- Partnership with TechCorp confirmed

ACTION ITEMS:
1. John Smith: Prepare detailed Q4 report by EOW
2. Sarah Johnson: Schedule customer feedback sessions
3. Mike Chen: Review and approve API documentation

NEXT STEPS:
- Follow-up meeting on February 1st
- Share notes with extended team`,

    email: `Subject: Meeting Summary - Product Strategy Discussion

Hi team,

Here's a summary of today's product strategy meeting:

Key Highlights:
• Q4 revenue exceeded targets by 12%
• AI features launching in Q2
• Partnership with TechCorp confirmed

Action Items:
• John: Q4 report due EOW
• Sarah: Schedule customer feedback sessions
• Mike: Review API documentation

Our next meeting is scheduled for February 1st.

Best regards,
AI Meeting Assistant`
  };

  const currentOutput = output || sampleOutputs[format];

  const handleCopy = async () => {
    await navigator.clipboard.writeText(currentOutput);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSaveEdit = () => {
    onEdit?.(editedOutput);
    setIsEditing(false);
  };

  const handleCancelEdit = () => {
    setEditedOutput(currentOutput);
    setIsEditing(false);
  };

  const getFormatIcon = (format: string) => {
    switch (format) {
      case 'json': return FileJson;
      case 'html': return FileCode;
      case 'email': return Mail;
      case 'plain': return FileText;
      default: return FileText;
    }
  };

  const FormatIcon = getFormatIcon(format);

  const renderPreview = () => {
    switch (format) {
      case 'markdown':
        return (
          <div className="prose prose-invert max-w-none">
            <div dangerouslySetInnerHTML={{ __html: convertMarkdownToHTML(currentOutput) }} />
          </div>
        );
      case 'json':
        return (
          <pre className="bg-slate-900/50 p-4 rounded-lg overflow-x-auto">
            <code className="text-sm text-slate-300">{currentOutput}</code>
          </pre>
        );
      case 'html':
        return viewMode === 'preview' ? (
          <div className="bg-white rounded-lg p-4">
            <iframe
              srcDoc={currentOutput}
              className="w-full h-96 border-0"
              title="HTML Preview"
            />
          </div>
        ) : (
          <pre className="bg-slate-900/50 p-4 rounded-lg overflow-x-auto">
            <code className="text-sm text-slate-300">{currentOutput}</code>
          </pre>
        );
      case 'email':
        return (
          <div className="bg-slate-900/50 rounded-lg p-4">
            <div className="space-y-3">
              <div>
                <span className="text-xs text-slate-500">SUBJECT:</span>
                <p className="text-white font-medium">{currentOutput.split('\n')[0].replace('Subject: ', '')}</p>
              </div>
              <div className="border-t border-white/10 pt-3">
                <pre className="whitespace-pre-wrap text-sm text-slate-300">
                  {currentOutput.split('\n').slice(2).join('\n')}
                </pre>
              </div>
            </div>
          </div>
        );
      default:
        return (
          <pre className="whitespace-pre-wrap text-sm text-slate-300 font-mono">
            {currentOutput}
          </pre>
        );
    }
  };

  // Simple markdown to HTML converter (in production, use a proper library)
  const convertMarkdownToHTML = (markdown: string) => {
    return markdown
      .replace(/^### (.*$)/gim, '<h3 class="text-lg font-semibold text-white mt-4 mb-2">$1</h3>')
      .replace(/^## (.*$)/gim, '<h2 class="text-xl font-bold text-white mt-6 mb-3">$1</h2>')
      .replace(/^# (.*$)/gim, '<h1 class="text-2xl font-bold text-white mb-4">$1</h1>')
      .replace(/^\* (.+)/gim, '<li class="text-slate-300 ml-4">$1</li>')
      .replace(/^- \[ \] (.+)/gim, '<li class="text-slate-300 ml-4">☐ $1</li>')
      .replace(/^- \[x\] (.+)/gim, '<li class="text-slate-300 ml-4">☑ $1</li>')
      .replace(/\*\*(.*)\*\*/g, '<strong class="font-semibold text-white">$1</strong>')
      .replace(/\*(.*)\*/g, '<em>$1</em>')
      .replace(/\n\n/g, '</p><p class="text-slate-300 mb-3">')
      .replace(/^/g, '<p class="text-slate-300 mb-3">')
      .replace(/$/g, '</p>')
      .replace(/<\/p><p class="text-slate-300 mb-3"><h/g, '</p><h')
      .replace(/<\/h(\d)><p class="text-slate-300 mb-3">/g, '</h$1>');
  };

  const Icon = app?.icon || FileText;
  const getColorClasses = (color: string) => {
    const colors: Record<string, { bg: string; text: string; icon: string; border: string }> = {
      blue: { bg: 'bg-blue-500/20', text: 'text-white', icon: 'text-blue-400', border: 'border-blue-500/30' },
      orange: { bg: 'bg-orange-500/20', text: 'text-white', icon: 'text-orange-400', border: 'border-orange-500/30' },
      purple: { bg: 'bg-purple-500/20', text: 'text-white', icon: 'text-purple-400', border: 'border-purple-500/30' },
      green: { bg: 'bg-green-500/20', text: 'text-white', icon: 'text-green-400', border: 'border-green-500/30' },
    };
    return colors[color || 'blue'] || colors.blue;
  };
  const colors = getColorClasses(app?.color || 'blue');

  return (
    <div className={`${isFullscreen ? 'fixed inset-0 z-50 bg-[#0a0a1a] p-6 overflow-auto' : 'space-y-6'}`}>
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          {app && (
            <div className={`w-10 h-10 ${colors.bg} ${colors.border} border rounded-lg flex items-center justify-center`}>
              <Icon className={`h-5 w-5 ${colors.icon}`} />
            </div>
          )}
          <div>
            <h2 className="text-xl font-bold text-white flex items-center gap-2">
              {app?.name || 'App'} Output
              {meetingTitle && (
                <Badge variant="outline" className="border-white/10 text-slate-400">
                  {meetingTitle}
                </Badge>
              )}
            </h2>
            <p className="text-sm text-slate-400">
              {timestamp || 'Generated just now'} • Format: {format.toUpperCase()}
            </p>
          </div>
        </div>
        {isFullscreen && (
          <Button
            variant="outline"
            size="icon"
            onClick={() => setIsFullscreen(false)}
            className="border-white/10 text-slate-400"
          >
            <X className="h-4 w-4" />
          </Button>
        )}
      </div>

      {/* Actions Bar */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {format === 'html' && (
            <Tabs value={viewMode} onValueChange={(v) => setViewMode(v as 'preview' | 'raw')}>
              <TabsList className="bg-slate-900/50 border border-white/10">
                <TabsTrigger value="preview">
                  <Eye className="h-4 w-4 mr-2" />
                  Preview
                </TabsTrigger>
                <TabsTrigger value="raw">
                  <Code className="h-4 w-4 mr-2" />
                  Raw
                </TabsTrigger>
              </TabsList>
            </Tabs>
          )}
          <Badge className="bg-slate-900/50 border-white/10 text-slate-400">
            <FormatIcon className="h-3 w-3 mr-1" />
            {format.toUpperCase()}
          </Badge>
        </div>

        <div className="flex items-center gap-2">
          {!isEditing ? (
            <>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setIsEditing(true)}
                className="border-white/10 text-slate-400"
              >
                <Edit className="h-4 w-4 mr-2" />
                Edit
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={handleCopy}
                className="border-white/10 text-slate-400"
              >
                {copied ? (
                  <>
                    <CheckCircle className="h-4 w-4 mr-2" />
                    Copied!
                  </>
                ) : (
                  <>
                    <Copy className="h-4 w-4 mr-2" />
                    Copy
                  </>
                )}
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() => onExport?.(format)}
                className="border-white/10 text-slate-400"
              >
                <Download className="h-4 w-4 mr-2" />
                Export
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={onRegenerate}
                className="border-white/10 text-slate-400"
              >
                <RefreshCw className="h-4 w-4 mr-2" />
                Regenerate
              </Button>
              {!isFullscreen && (
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => setIsFullscreen(true)}
                  className="border-white/10 text-slate-400"
                >
                  <Maximize2 className="h-4 w-4" />
                </Button>
              )}
            </>
          ) : (
            <>
              <Button
                variant="outline"
                size="sm"
                onClick={handleCancelEdit}
                className="border-white/10 text-slate-400"
              >
                Cancel
              </Button>
              <Button
                size="sm"
                onClick={handleSaveEdit}
                className="bg-purple-600 hover:bg-purple-700 text-white"
              >
                <Save className="h-4 w-4 mr-2" />
                Save Changes
              </Button>
            </>
          )}
        </div>
      </div>

      {/* Output Content */}
      <CardGlass>
        <CardGlassContent className="p-6">
          {isEditing ? (
            <Textarea
              value={editedOutput}
              onChange={(e) => setEditedOutput(e.target.value)}
              className="w-full min-h-[400px] bg-slate-900/50 border-white/10 text-white font-mono text-sm"
              placeholder="Edit the output..."
            />
          ) : (
            <div className="min-h-[400px]">
              {renderPreview()}
            </div>
          )}
        </CardGlassContent>
      </CardGlass>

      {/* Export Options */}
      {!isEditing && (
        <Alert className="bg-blue-500/10 border-blue-500/30">
          <Sparkles className="h-4 w-4 text-blue-400" />
          <AlertDescription className="text-blue-300">
            <div className="flex items-center justify-between">
              <span>Export this output in different formats</span>
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onExport?.('pdf')}
                  className="text-blue-400 hover:text-blue-300"
                >
                  PDF
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onExport?.('docx')}
                  className="text-blue-400 hover:text-blue-300"
                >
                  Word
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onExport?.('txt')}
                  className="text-blue-400 hover:text-blue-300"
                >
                  Text
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => onExport?.(format)}
                  className="text-blue-400 hover:text-blue-300"
                >
                  Original
                </Button>
              </div>
            </div>
          </AlertDescription>
        </Alert>
      )}

      {/* Navigation (when in a series) */}
      {!isEditing && (
        <div className="flex items-center justify-between">
          <Button
            variant="ghost"
            size="sm"
            className="text-slate-400"
            disabled
          >
            <ChevronLeft className="h-4 w-4 mr-2" />
            Previous Output
          </Button>
          <span className="text-sm text-slate-500">1 of 1</span>
          <Button
            variant="ghost"
            size="sm"
            className="text-slate-400"
            disabled
          >
            Next Output
            <ChevronRight className="h-4 w-4 ml-2" />
          </Button>
        </div>
      )}
    </div>
  );
}